<?php

namespace AppBundle\Repository;

/**
 * VadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VadeRepository extends \Doctrine\ORM\EntityRepository
{
}
